numeros-aleatorios: 100000
semente: 25478
filas:
  - id: 0
    capacidade: -1
    chegada-inicial: 1.0
    chegada-minima: 1.0
    chegada-maxima: 4.0
    saida-minima: 1.0
    saida-maxima: 1.5
    servidores: 1

  - id: 1
    servidores: 3
    capacidade: 5
    saida-minima: 5.0
    saida-maxima: 10.0

  - id: 2
    servidores: 2
    capacidade: 8
    saida-minima: 10.0
    saida-maxima: 20.0

redes:
  - origem: 0
    destino: 1
    probabilidade: 0.8
  - origem: 0
    destino: 2
    probabilidade: 0.2
  - origem: 1
    destino: 0
    probabilidade: 0.3
  - origem: 1
    destino: 2
    probabilidade: 0.5
  - origem: 2
    destino: 1
    probabilidade: 0.7

